### PR TITLE
Unification and Improved Flow

### PR DESCRIPTION
**Pull request by 0111narwhalz**

### CODE REVIEW

**Comment by TotallyNotHuman** [comment]
Um, ideally, you should have told this PR to merge to the `release/1.0.0` branch, which I can then merge _back_ to `develop` (and terminate `release/1.0.0`, because this so-called release has dragged on for 4 release candidates now). If I merge this now, there will be a metric mulchload of merge conflicts, which gets downright ugly.
Is it possible to change the target branch to `release/1.0.0`?

**Comment by TotallyNotHuman** [comment]
Welp, nothing we can do about it now. The damage is done.
`release/1.0.0` will be terminated, all the tags removed. KSPNameGen will revert to a beta state.
Now, about the thread; is there any way you can close it temporarily? I think `moderators` is the key.

**Comment by 0111narwhalz** [comment]
Lemme see if I can do that. Otherwise, I'll resubmit the pull w/ a new target.

**Comment by TotallyNotHuman** [comment]
Gah, m***e. I merged already.

**Comment by 0111narwhalz** [comment]
I don't see any buttons to do that.

**Comment by 0111narwhalz** [comment]
Okay, I need to read before commenting.

**Comment by TotallyNotHuman** [comment]
Ah well. Try submitting with a new target, and I'll revert this PR again.

**Comment by TotallyNotHuman** [comment]
So do I.

**Pull request merged**
