### PR TITLE
Revert "Unification and Improved Flow"

### PR DESCRIPTION
**Pull request by TotallyNotHuman**
Reverts TotallyNotHuman/KSPNameGen#3

### CODE REVIEW

**Comment by 0111narwhalz** [comment]
So what do you think?

**Comment by TotallyNotHuman** [comment]
It looks solid to me. There's just the teensy little problem of mistaken identity.
How's the new PR going? Any trouble that I need to know about?

**Comment by 0111narwhalz** [comment]
Says there's nothing to compare.

**Comment by TotallyNotHuman** [comment]
Huh, that's interesting. Let me try to create the PR.

**Comment by TotallyNotHuman** [comment]
Well...um...crap. I done screwed up.
I deleted the release/1.0.0 branch.
Oh, whatever; I'll just revert this PR once again.

**Comment by 0111narwhalz** [comment]
We are the _most_ competent of the programmers!

**Comment by TotallyNotHuman** [comment]
Not so much programmers; more so VCS operators.

**Comment by 0111narwhalz** [comment]
Whoops, sorry about the poof.
What's going on with the PR and the code?

**Comment by TotallyNotHuman** [comment]
No worries. Check out #5. Your unification has been merged into `develop`; I'll check for 🐛s and fix accordingly.

**Pull request merged**
