### PR TITLE
Nuked infinite recursion and bugfixes

### PR DESCRIPTION
**Pull request by 0111narwhalz**

### CODE REVIEW

**Comment by TotallyNotHuman** [comment]
What the...!

I thought `goto` was a reserved keyword and couldn't do anything!

**Comment by 0111narwhalz** [comment]
Heh.
I don't know how to respect taboos. It was of utility, and damn the stigma.

**Comment by 0111narwhalz** [comment]
Anyway, the code needs more than a half-hour hack. I don't really know why you put everything in different files either; it doesn't seem to be necessary.

**Comment by TotallyNotHuman** [comment]
No, I don't mind you blatantly violate clearly-defined programming taboos and damn the consequence, but this is totally different.
I tried using `goto` in NB. It refused to compile. `goto` just doesn't do anything.
Ref: [stackoverflow.com/questions/2545103/is-there-a-goto-statement-in-java](stackoverflow.com/questions/2545103/is-there-a-goto-statement-in-java)

**Comment by 0111narwhalz** [comment]
Well, `goto` can't work alone. It's a two-part keyword. You need an anchor to which the `goto` might refer.

**Comment by TotallyNotHuman** [comment]
I will admit that it probably isn't necessary to put everything in different files. I have my programming wrongdoings, and you have yours.
I'll merge this PR and see if it'll compile. If not...well, we'll cross that bridge when we come to it.

**Comment by TotallyNotHuman** [comment]
I'm reopening this thread, because there are some problems.
First of all, your problem with killing the `args` from `blah.main();`. You have to also kill the corresponding end: `static void main(String[] args) throws InterruptedException` has to turn into `static void main() throws InterruptedException`. That I can take care of, no problemo.
The next, and more pressing matter are the `goto`s. It just doesn't work.
Why not? Let me count the ways. This is an excerpt from the compiler stacktrace.
```
Compiling 4 source files to C:\Users\[OMITTED]\Documents\NetBeansProjects\KSPNameGen\build\classes
C:\Users\[OMITTED]\Documents\NetBeansProjects\KSPNameGen\src\kspnamegen\nameGen.java:135: error: illegal start of expression
goto surname;
C:\Users\[OMITTED]\Documents\NetBeansProjects\KSPNameGen\src\kspnamegen\nameGen.java:135: error: not a statement
goto surname;
C:\Users\[OMITTED]\Documents\NetBeansProjects\KSPNameGen\src\kspnamegen\nameGen.java:142: error: illegal start of expression
goto surname;
C:\Users\[OMITTED]\Documents\NetBeansProjects\KSPNameGen\src\kspnamegen\nameGen.java:142: error: not a statement
goto surname;
C:\Users\[OMITTED]\Documents\NetBeansProjects\KSPNameGen\src\kspnamegen\nameGen.java:160: error: illegal start of expression
goto firstName;
C:\Users\[OMITTED]\Documents\NetBeansProjects\KSPNameGen\src\kspnamegen\nameGen.java:160: error: not a statement
goto firstName;
C:\Users\[OMITTED]\Documents\NetBeansProjects\KSPNameGen\src\kspnamegen\nameGen.java:194: error: illegal start of expression
goto gender;
C:\Users\[OMITTED]\Documents\NetBeansProjects\KSPNameGen\src\kspnamegen\nameGen.java:194: error: not a statement
goto gender;
C:\Users\[OMITTED]\Documents\NetBeansProjects\KSPNameGen\src\kspnamegen\nameGen.java:205: error: illegal start of expression
goto number;
C:\Users\[OMITTED]\Documents\NetBeansProjects\KSPNameGen\src\kspnamegen\nameGen.java:205: error: not a statement
goto number;
C:\Users\[OMITTED]\Documents\NetBeansProjects\KSPNameGen\src\kspnamegen\nameGen.java:210: error: illegal start of expression
goto number(args);
11 errors
C:\Users\[OMITTED]\Documents\NetBeansProjects\KSPNameGen\nbproject\build-impl.xml:930: The following error occurred while executing this line:
C:\Users\[OMITTED]\Documents\NetBeansProjects\KSPNameGen\nbproject\build-impl.xml:270: Compile failed; see the compiler error output for details.
BUILD FAILED (total time: 0 seconds)
```
QED.

**Comment by 0111narwhalz** [comment]
Ugh. Alright, roll it back.
I'm gonna do this right. No allegedly deprecated `goto`s. No dodgy mishmash of old code and new.

**Comment by TotallyNotHuman** [comment]
Gotcha. In the meantime, I'll just do a revert-commit.

**Pull request merged**
